import { meta } from '~/lib/data'

export function Footer() {
  const generated = new Date(meta.generatedAt)
  const datestamp = isNaN(generated.getTime())
    ? meta.generatedAt
    : generated.toISOString().slice(0, 10)
  return (
    <footer className="border-base-divider-subtle text-base-content-medium mt-12 border-t">
      <div className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-6 text-xs sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8">
        <span>
          Data refreshed {datestamp} · {meta.totalBriefs} briefs ·{' '}
          {meta.totalDigests} digests
        </span>
        <span>
          Generated by the{' '}
          <a
            href="https://github.com/luarss/etp-hermes"
            className="hover:text-base-content-default underline underline-offset-2"
          >
            etp-hermes
          </a>{' '}
          pipeline
        </span>
      </div>
    </footer>
  )
}
